config/routes.rb
Thrasys::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users

  root :to => 'home#index'
  match '/technology' => 'static#technology'
  match '/solutions' =>  'static#solutions'

end

app/models/solution.rb
class Solution < ActiveRecord::Base
  has_attached_file :image, :styles => { :small => "150x150>", :medium => "300X300", :large => "600X600" }
  validates_attachment_presence :image
  validates_attachment_size :image, :less_than => 5.megabytes
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
  validates_presence_of :tab_title
  validates_presence_of :title
  validates_presence_of :description
end

app/controllers/admin/solutions_controller.rb
class Admin::SolutionsController < AbstractAdminController
  # GET /solutions
  # GET /solutions.json
  def index
    @solutions = Solution.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @solutions }
    end
  end

  # GET /solutions/1
  # GET /solutions/1.json
  def show
    @solution = Solution.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @solution }
    end
  end

  # GET /solutions/new
  # GET /solutions/new.json
  def new
    @solution = Solution.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @solution }
    end
  end

  # GET /solutions/1/edit
  def edit
    @solution = Solution.find(params[:id])
  end

  # POST /solutions
  # POST /solutions.json
  def create
    @solution = Solution.new(params[:solution])

    respond_to do |format|
      if @solution.save
        format.html { redirect_to '/admin/solutions', notice: 'Solution was successfully created.' }
        format.json { render json: @solution, status: :created, location: @solution }
      else
        format.html { render action: "new" }
        format.json { render json: @solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /solutions/1
  # PUT /solutions/1.json
  def update
    @solution = Solution.find(params[:id])

    respond_to do |format|
      if @solution.update_attributes(params[:solution])
        format.html { redirect_to '/admin/solutions', notice: 'Solution was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solutions/1
  # DELETE /solutions/1.json
  def destroy
    @solution = Solution.find(params[:id])
    @solution.destroy

    respond_to do |format|
      format.html { redirect_to admin_solutions_url }
      format.json { head :ok }
    end
  end
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/views/admin/solutions/_form.html.erb
<%= form_for [:admin, @solution], :html => { :multipart => true } do |f| %>
  <% if @solution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@solution.errors.count, "error") %> prohibited this solution from being saved:</h2>

      <ul>
      <% @solution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :tab_title %><br />
    <%= f.text_field :tab_title %>
  </div>
  <div class="field">
    <%= f.label :sort_order %><br />
    <%= f.number_field :sort_order %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/solutions/edit.html.erb
<h1>Editing solution</h1>

<%= render 'form' %>

<%= link_to 'Back', solutions_path %>

app/views/admin/solutions/index.html.erb
<h1>Listing solutions</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Sort order</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @solutions.each do |solution| %>
  <tr>
    <td><%= solution.title %></td>
    <td><%= solution.sort_order %></td>
    <td><%= link_to 'Edit', edit_admin_solution_path(solution) %></td>
    <td><%= link_to 'Destroy', [:admin, solution], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Solution', new_admin_solution_path %>

app/views/admin/solutions/new.html.erb
<h1>New solution</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_solutions_path %>

app/views/admin/solutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @solution.description %>
</p>

<p>
  <b>Sort order:</b>
  <%= @solution.sort_order %>
</p>


<%= link_to 'Edit', edit_solution_path(@solution) %> |
<%= link_to 'Back', solutions_path %>